# Generated by Django 4.2.3 on 2024-08-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myself',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=16)),
                ('my_email', models.EmailField(max_length=254, unique=True, verbose_name='my email ID')),
                ('subject', models.CharField(max_length=150)),
                ('resume', models.FileField(upload_to='files')),
                ('mailbody', models.TextField()),
            ],
        ),
    ]
