# Generated by Django 5.0 on 2024-01-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plot_no',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('', ''), ('Cash on Delivery', 'COD'), ('Debit/Credit Card', 'Debit/Credit Card'), ('UPI', 'UPI')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('', ''), ('Cash on Delivery', 'COD'), ('Debit/Credit Card', 'Debit/Credit Card'), ('UPI', 'UPI')], max_length=50),
        ),
    ]
